name: hello-world

'on': pull_request
jobs:
  integration-tests:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run integration tests
      run: |
        python3 -m pytest

    - name: Final checks
      run: |
        # Add any additional checks or commands to verify the success of the tests
      working-directory: webapp
