name: Integration Test

'on':
    pull_request:
      branches: main
jobs:
  integration-tests:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Run integration tests
      run: |
        python3 -m pytest
