name : CI

on:
  pull_request:

jobs:
  run-tests:
    runs-on: self-hosted

    
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: |
          echo "Running tests"
          pytest tests
          echo "Tests passed"

      - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
