name: Integration Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pytest

    - name: Run tests
      run: |
        pytest webapp/tests

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to Cloud (replace with your deployment steps)
      run: |
        # Add your deployment steps here

  merge:
    needs: [test, deploy]
    runs-on: ubuntu-latest

    steps:
    - name: Merge pull request
      uses: actions/github-script@0.9.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const prNumber = context.payload.pull_request.number;
          await github.pulls.merge({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: prNumber
          });

