name : CI

on:
  pull_request:

jobs:
  run-tests:
    runs-on: self-hosted

    
    steps:
      - name: Run tests
        run: |
          echo "Running tests"
          pytest tests
          echo "Tests passed"
